version: "3"
services:
  develop:
    build: .
    ports:
      - "5100:5100"
    env_file:
       - .env
    container_name: aqueduct_analysis-develop
    environment:
      PORT: 5100
      CT_REGISTER_MODE: auto
      ENVIRONMENT: dev
      DEBUG: "True"
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      API_VERION: v1
      POSTGRES_URL: postgresql+psycopg2://postgres@postgres:5432/flood_v2
    command: develop
    volumes:
      - ./aqueduct:/opt/aqueduct/aqueduct
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.12
    container_name: aqueduct-postgres
    ports:
      - "5432:5432"
    volumes:
      - ${LOCAL_DATABASE}:/data
      - ./data:/data_import
  
  pgadmin-aq:
    image: dpage/pgadmin4
    container_name: pgadmin-aq
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@vizzuality.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
