version: "3"
services:
  test:
    build: .
    ports:
      - "5100:5100"
    container_name: aqueduct_analysis-test
    environment:
      PORT: 5700
      CT_REGISTER_MODE: "False"
      ENVIRONMENT: dev
      DEBUG: "True"
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      POSTGRES_URL: postgresql://postgres@postgres:5432/flood
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5700
    command: test
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.12
    container_name: aqueduct-postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: flood
