apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: aqueduct
  labels:
    name: aqueduct-analysis
  name: aqueduct-analysis
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: aqueduct-analysis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - name: aqueduct-analysis
          image: vizzuality/aqueduct-analysis
          imagePullPolicy: Always
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
          args:
            - start
          env:
            - name: PORT
              value: "5700"
            - name: ENVIRONMENT
              value: staging
            - name: LOGGER_LEVEL
              value: DEBUG
            - name: LOCAL_URL
              value: http://aqueduct-analysis.aqueduct.svc.cluster.local:5700
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
            - name: CARTODB_USER
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CARTODB_USER
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: AQUEDUCT_POSTGRES_URL
            - name: AQUEDUCT_GOOGLE_PLACES_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: AQUEDUCT_GOOGLE_PLACES_PRIVATE_KEY

          ports:
            - containerPort: 5700

      restartPolicy: Always
