apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: aqueduct-analysis
  name: aqueduct-analysis
  namespace: aqueduct
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: aqueduct-analysis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aqueduct-analysis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "5700"
            - name: ENVIRONMENT
              value: staging
            - name: LOGGER_LEVEL
              value: DEBUG
            - name: LOCAL_URL
              value: http://aqueduct-analysis.aqueduct.svc.cluster.local:5700
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  key: CT_URL
                  name: mssecrets
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CT_TOKEN
                  name: mssecrets
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  key: CT_REGISTER_MODE
                  name: mssecrets
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  key: API_VERSION
                  name: mssecrets
            - name: CARTODB_USER
              valueFrom:
                secretKeyRef:
                  key: CARTODB_USER
                  name: mssecrets
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  key: AQUEDUCT_POSTGRES_URL
                  name: dbsecrets
            - name: AQUEDUCT_GOOGLE_PLACES_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: AQUEDUCT_GOOGLE_PLACES_PRIVATE_KEY
                  name: appsecrets
          image: gfwdockerhub/aqueduct-analysis
          imagePullPolicy: Always
          name: aqueduct-analysis
          ports:
            - containerPort: 5700
              protocol: TCP
          resources:
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
